
name: 'My Governance Dashboard'

zmqMonitoring:
  connections:
    - url: 'tcp://localhost:7070'
      #type: 'SUB'
      #serializationClass: 'org.neo.gomina.model.monitoring.zmq.ZmqMonitorThread'
    - url: 'tcp://localhost:7071'
