
name: 'My Governance Dashboard'
port: 8080
passwordsFile: 'config/pass.properties'

domains:
  - 'local'

jiraUrl: 'http://localhost/jira'
jiraProjects:
  - 'DEMO'
  - 'TEST'
  - 'JIRA'

database:
  host: 'localhost'
  port: '7080'

maven:
  localRepository: '~/.m2'
  remoteRepositories:
    - id: 'central'
      type: 'default'
      url: 'https://repo.maven.apache.org/maven2/'

monitoring:
  timeout: 4

interactions:
  file: 'datadummy/interactions2.json'

events:
  internalMonitoring:
    - id: 'internal'
  elasticSearch:
    - id: 'releases'
      host: 'localhost'
      port: 9200
      envId: 'env'
      instanceId: 'instance'
    - id: 'logs'
      host: 'localhost'
      port: 9300
  dummy:
    - id: 'dummy'
      file: 'datadummy/events.json'

jenkins:
  servers:
    - id: 'vaction'
      location: 'http://default-jenkins/jenkins/'
    - id: 'principal'
      location: 'http://localhost:7111/jenkins/'
    - id: 'local'
      location: 'http://localhost:8081/job/'
    - id: 'edge'
      location: 'https://jenkins.io/edge/'
    - id: 'apache'
      location: 'https://builds.apache.org/job/'
    
sonar:
  servers:
    - id: 'main'
      mode: 'http'
      url: 'http://localhost:9000'
    - id: 'dummy'
      mode: 'dummy'
