
name: 'My Governance Dashboard'

scm:
  repos:
    - id: 'vac'
      type: 'svn'
      location: 'http://svn/actions/venteaction/vaction/Developpement/'
    - id: 'home'
      type: 'svn'
      location: 'file:////Users/Amokrane/Work/SvnRepo/svn-repo-demo/'
      username: 'amokrane'
      passwordAlias: '@amokrane'
    - id: 'dummy'
      type: 'dummy'
      location: ''

zmqMonitoring:
  connections:
    - url: 'tcp://localhost:7070'
      #type: 'SUB'
      #serializationClass: 'org.neo.gomina.model.monitoring.zmq.ZmqMonitorThread'
    - url: 'tcp://localhost:7071'
