
name: 'My Governance Dashboard'
passwordsFile: 'config/pass.properties'

inventory:
  #projectsFile: 'data/projects.json'
  projectsFile: 'data/projects.yaml'
  inventoryDir: 'data'
  #inventoryFilter: 'env\.(.*?)\..*'
  inventoryFilter: 'env\.(.*?)\.yaml'
  #inventoryFilter: 'env\.(.*i.*?)\.yaml'

scm:
  repos:
    - id: 'vac'
      type: 'svn'
      location: 'http://svn/actions/venteaction/vaction/Developpement/'
    - id: 'home'
      type: 'svn'
      location: 'file:////Users/Amokrane/Work/SvnRepo/svn-repo-demo/'
      username: 'amokrane'
      passwordAlias: '@amokrane'
    - id: 'dummy'
      type: 'dummy'
      location: 'dummy://'

sonar:
  servers:
    - id: ''
      mode: 'http'
      url: 'http://localhost:9000'
    - id: 'main'
      mode: 'dummy'
    - id: 'dummy'
      mode: 'dummy'

jenkins:
  servers:
    - id: ''
      location: 'http://default-jenkins/jenkins/'
    - id: 'principal'
      location: 'http://localhost:7111/jenkins/'
    - id: 'edge'
      location: 'https://jenkins.io/edge/'
    - id: 'apache'
      location: 'https://builds.apache.org/job/'

ssh:
  hosts:
    - host: 'localhost'
      username: 'Amokrane'
      passwordAlias: '@amokrane'
      sudo: ''

zmqMonitoring:
  connections:
    - url: 'tcp://localhost:7070'
      #type: 'SUB'
      #serializationClass: 'org.neo.gomina.plugins.monitoring.zmq.ZmqMonitorThread'
    - url: 'tcp://localhost:7071'
